core/urls.py
from django.urls import path, re_path

from core.views import (
    maps_view,
    map_view,
    polygons_view,
    add_map,
    get_polygons,
    polygon_export,
    about,
    charts_view,
    chart_view,
    plots_view,
    plot_view,
    log_in,
    log_out,
    new_style_map_view,
)

app_name = "Maps"

urlpatterns = [
    path("", maps_view, name="maps"),
    path("charts", charts_view, name="charts"),
    path("plots", plots_view, name="plots"),
    path("map/<str:slug>", map_view, name="map"),
    path("new-style-map/<str:slug>", new_style_map_view, name="new_style_map"),
    path("chart/<str:slug>", chart_view, name="chart"),
    path("plot/<str:slug>", plot_view, name="plot"),
    path("plot/<str:slug>/<str:key>", plot_view, name="plot_key"),
    re_path("world/", polygons_view, name="polygons"),
    path("polygon/<int:pk>/geojson", polygon_export, name="polygon_export"),
    path("user/<str:username>/maps", maps_view, name="user_maps"),
    path("user/<str:username>/charts", charts_view, name="user_charts"),
    path("add/map", add_map, name="add_map"),
    path("api/get-polygons/<str:parent_id>", get_polygons, name="get_polygons"),
    path("about", about, name="about"),
    path("login", log_in, name="login"),
    path("logout", log_out, name="logout"),
]

maps/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.utils.translation import ugettext_lazy as _

from core.sitemaps import (
    StaticPagesSitemap,
    MapsSitemap,
    ChartsSitemap,
    CovidMapsSitemap,
    CovidChartsSitemap,
)

from covid.views import covid_19_view, covid_19_country_view

sitemaps = {
    "maps": MapsSitemap,
    "charts": ChartsSitemap,
    "static_pages": StaticPagesSitemap,
    "covid_maps": CovidMapsSitemap,
    "covid_charts": CovidChartsSitemap,
}

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("covid", covid_19_view, name="covid"),
    path("covid/<str:key>", covid_19_view, name="covid_key"),
    path("covid-country/<str:country>", covid_19_country_view, name="covid_country"),
    path(
        "covid-country/<str:country>/<str:key>",
        covid_19_country_view,
        name="covid_country_key",
    ),
    path("accounts/", include("allauth.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("admin/", admin.site.urls),
]

admin.site.site_header = _("Maps administration")

if settings.DEBUG:
    from django.conf.urls.static import static
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

core/models.py
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.core.cache import cache
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from djgeojson.fields import MultiPolygonField
from mptt.models import MPTTModel, TreeForeignKey

from core.widgets import ColorWidget


def get_unique_slug(cls, title: str) -> str:
    """ Helper function to get unique slug. """
    unique_slug = slug = slugify(title)
    num = 1
    while cls.objects.filter(slug=unique_slug).exists():
        unique_slug = f"{slug}-{num}"
        num += 1
    return unique_slug


class ColorField(models.CharField):
    """ Color field. """

    def formfield(self, **kwargs):
        kwargs["widget"] = ColorWidget
        return super().formfield(**kwargs)


class Category(models.Model):
    """ Category model. """

    title = models.CharField(max_length=60, unique=True)
    description = models.TextField(blank=True, null=True)
    slug = models.SlugField(editable=False)

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        if not self.pk:
            self.slug = slugify(self.title)

        super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return self.title


class Polygon(MPTTModel):
    """ Polygon model. """

    title = models.CharField(max_length=256)
    geom = MultiPolygonField()
    parent = TreeForeignKey(
        "self",
        null=True,
        blank=True,
        related_name="children",
        db_index=True,
        on_delete=models.CASCADE,
    )

    class MPTTMeta:
        order_insertion_by = ["title"]

    def __str__(self):
        return self.title

    def geojson(self, data: int = 0, path: str = "") -> str:
        return (
            "{{"
            '"type": "Feature", '
            '"id": "{}", '
            '"properties": {{'
            '"name": "{}", "density": {}, "path": "{}"'
            "}}, "
            '"geometry": {}'
            "}}, ".format(self.pk, self.title, data, path, self.geom)
        )


class Map(models.Model):
    """ Map model. """

    title = models.CharField(
        max_length=256, verbose_name=_("title"), help_text="Map title."
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name=_("description"),
        help_text="Map description.",
    )
    unit = models.CharField(
        blank=True,
        max_length=64,
        verbose_name=_("unit"),
        help_text="The unit that will be used for the map.",
    )
    date_of_information = models.DateField(
        default=timezone.now,
        blank=True,
        verbose_name=_("date"),
        help_text="An year or date when the information was measured.",
    )
    region = models.ForeignKey(
        Polygon,
        blank=True,
        null=True,
        verbose_name=_("region"),
        related_name="maps",
        on_delete=models.CASCADE,
    )
    categories = models.ManyToManyField(
        Category, blank=True, verbose_name=_("categories"), related_name="maps"
    )
    grades = models.PositiveSmallIntegerField(
        default=8,
        verbose_name=_("grades"),
        help_text="How many grades you would like to have",
    )
    logarithmic_scale = models.BooleanField(
        default=False,
        verbose_name=_("logarithmic scale"),
        help_text="If True - logarithmic scale will be used.",
    )
    end_color = ColorField(
        max_length=6,
        default="ffeda0",
        verbose_name=_("end color"),
        help_text="The color to fill regions with the lowest value.",
    )
    start_color = ColorField(
        max_length=6,
        default="bd0026",
        verbose_name=_("start color"),
        help_text="The color to fill regions with the highest value.",
    )
    opacity = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=0.7,
        validators=[MinValueValidator(0), MaxValueValidator(1)],
        verbose_name=_("opacity"),
        help_text="The opacity for regions.",
    )
    changed = models.DateTimeField(
        auto_now=True,
        verbose_name=_("changed"),
        help_text="Time when map was changed last time.",
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="maps",
        verbose_name=_("user"),
        help_text="Map owner.",
        on_delete=models.CASCADE,
    )
    slug = models.SlugField(
        editable=False,
        verbose_name=_("slug"),
        help_text="The slug that will be user for urls.",
    )

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        if not self.pk:
            self.slug = get_unique_slug(type(self), self.title)

        cache.delete_pattern("*:map_view:" + self.slug)
        cache.delete_pattern("*:maps")
        super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return self.title


class MapElement(models.Model):
    """ MapElement model. """

    map = models.ForeignKey(Map, related_name="elements", on_delete=models.CASCADE)
    polygon = models.ForeignKey(
        Polygon, related_name="polygon_elements", on_delete=models.CASCADE
    )
    data = models.FloatField()

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        cache.delete_pattern("*:map_view:" + self.map.slug)
        super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return self.polygon.title

    def geojson(self) -> str:
        return (
            "{{"
            '"type": "Feature", '
            '"id": "{}", '
            '"properties": {{"name": "{}", "density": {}}}, '
            '"geometry": {}'
            "}}, ".format(self.pk, self.polygon.title, self.data, self.polygon.geom)
        )


class Chart(models.Model):
    """ Chart model. """

    title = models.CharField(max_length=256)
    description = models.TextField(
        blank=True, null=True, help_text="Chart description."
    )
    maps = models.ManyToManyField(Map, related_name="charts")
    changed = models.DateTimeField(
        auto_now=True,
        verbose_name=_("changed"),
        help_text="Time when chart was changed last time.",
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="charts",
        help_text="Map owner.",
        on_delete=models.CASCADE,
    )
    slug = models.SlugField(
        editable=False, help_text="The slug that will be user for urls."
    )

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        if not self.pk:
            self.slug = get_unique_slug(type(self), self.title)
        super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return self.title


class Plot(models.Model):
    """ Plot model. """

    slug = models.CharField(max_length=256)
    data = models.JSONField(default=dict, blank=True)
    added = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="plots",
        verbose_name=_("user"),
        help_text="Plot owner.",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f"{self.slug}-{self.added}"

templates/about.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "About us" %}{% endblock title %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="mb-4"><wbr>{% trans "About us" %}</h1>
            <p>{% trans "With this site you can build statistic interactive webmaps." %}</p>
            <p>{% trans "Link to the repository:" %} <a href="https://bitbucket.org/voron-raven/maps">https://bitbucket.org/voron-raven/maps</a></p>
            <p>{% trans "Site owner:" %} <a href="https://www.linkedin.com/in/mykhailokeda/">Mykhailo Keda</a></p>
        </div>
    </div>
{% endblock content %}

templates/base.html
<!doctype html>
{% load static %}
{% load leaflet_tags %}
{% load i18n %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABoklEQVR42n3TSyhmYRzH8fOKZKQpCwvNNGKhFBOxUFMGUVKKZqEsmCzGwm0hG80kt0TZyMKdkBjZYKTJLTaSKEozjSJq1CwsMJlJ+P7rdzje5KnPW+c8z/k9l//z+hzH2UInxvHPeWiZqMeL5/p9/NziGmfowSZqkKqP7H2xPvb2v7MUNyAPUShHjD4cwqJmC0OJX/8aut2AdIQrcFuDWvEBXzCDP/iJv3iDCJvADbBBicjHfwygA2NI8ey7FocYRr+tyA14jwJUauAgplCKY723sZcIxjxGMOkNaEGcZviBT8iWIoR4VvIVEzaJN2ADC+jCjvb7S+dh7Uar8Ol5DrnegFUE4TtO0YZlhGrMPk6QgyM0W1n9A6w8hZphSdvIsHKhGgk6Hwu9wop/QK5Kdq59zyIW64jEZ1XsLaIx7R/g6IQDkaXneDSoxEEaa2dVZwf/VIDtfVdlCtYhJmFU/R/xCr/R6wbYxWjEAV7rWtveqxCgfXepKtZeosm9SHZZKrTUb9hDGS50na88/fNa3X2/W1NraRqYjHb0OY//vk/23wHtsXwyEoeUBgAAAABJRU5ErkJggg==" rel="icon"/>
  <link rel="stylesheet" type="text/css" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'easy_select2/vendor/select2/css/select2.min.css' %}"/>
  <title>{% block title %}{% trans "Maps" %}{% endblock title %}</title>
  <meta name="description" content="{% block description %}{% trans 'Statistic interactive webmaps.' %}{% endblock description %}">
  <meta name="keywords" content="Map,Webmap,Leaflet,GeoJSON">
  <meta property="og:title" content="{% block og-title %}{% trans 'Maps' %}{% endblock og-title %}">
  <meta property="og:type" content="website">
  <meta property="og:description" content="{% block og-description %}{% trans 'Statistic interactive webmaps.' %}{% endblock og-description %}">
  {% leaflet_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
  {% block css %}{% endblock css %}
</head>
<body>
<svg class="hidden-xl-down">
  <defs>
    <symbol id="chat-icon" viewBox="0 0 14 14">
      <path d="M7,0.935c-3.866,0-7,2.463-7,5.5c0,1.438,0.703,2.749,1.854,3.729   c-0.044,0.955-0.242,2.239-0.942,2.901c1.337,0,2.706-0.88,3.518-1.514c0.796,0.248,1.663,0.384,2.57,0.384c3.866,0,7-2.463,7-5.5   S10.866,0.935,7,0.935z" fill="#006DF0"/>
    </symbol>
  </defs>
</svg>
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top hidden-print">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto">
        {% url 'core:maps' as maps_url %}
        <li class="nav-item {% if request.get_full_path == maps_url %}active{% endif %}">
          <a class="nav-link" href="{{ maps_url }}">{% trans "Maps" %} <span class="sr-only">(current)</span></a>
        </li>
        {% url 'core:charts' as charts_url %}
        <li class="nav-item {% if request.get_full_path == charts_url %}active{% endif %}">
          <a class="nav-link" href="{{ charts_url }}">{% trans "Charts" %}</a>
        </li>
        {% url 'core:plots' as plots_url %}
        <li class="nav-item {% if request.get_full_path == plots_url %}active{% endif %}">
          <a class="nav-link" href="{{ plots_url }}">{% trans "Plots" %}</a>
        </li>
        {% url 'core:about' as about_url %}
        <li class="nav-item {% if request.get_full_path == about_url %}active{% endif %}">
          <a class="nav-link" href="{{ about_url }}">{% trans "About" %}</a>
        </li>
      </ul>
      <ul class="navbar-nav mr-right">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{% trans "COVID-19 maps" %}</a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="nav-link text-muted ml-2" href="{% url 'covid_key' 'cases' %}">{% trans "cases" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'covid_key' 'deaths' %}">{% trans "deaths" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'covid_key' 'total_recovered' %}">{% trans "total recovered" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'covid_key' 'active_cases' %}">{% trans "active cases" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'covid_key' 'new_deaths' %}">{% trans "new deaths" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'covid_key' 'new_cases' %}">{% trans "new cases" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'covid_key' 'serious_critical' %}">{% trans "serious critical" %}</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{% trans "COVID-19 charts" %}</a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="nav-link text-muted ml-2" href="{% url 'core:plot_key' 'covid' 'cases' %}">{% trans "cases" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'core:plot_key' 'covid' 'deaths' %}">{% trans "deaths" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'core:plot_key' 'covid' 'total_recovered' %}">{% trans "total recovered" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'core:plot_key' 'covid' 'active_cases' %}">{% trans "active cases" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'core:plot_key' 'covid' 'new_deaths' %}">{% trans "new deaths" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'core:plot_key' 'covid' 'new_cases' %}">{% trans "new cases" %}</a>
            <a class="nav-link text-muted ml-2" href="{% url 'core:plot_key' 'covid' 'serious_critical' %}">{% trans "serious critical" %}</a>
          </div>
        </li>
        {% url 'core:polygons' as polygons_url %}
        <li class="nav-item {% if request.get_full_path == polygons_url %}active{% endif %}">
          <a class="nav-link" href="{{ polygons_url }}">
            {% trans "Available polygons" %}
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Add" %}</a>
          <div class="dropdown-menu dropdown-menu-right">
            {% url 'core:add_map' as add_map_url %}
            <a class="nav-link text-muted ml-2{% if request.get_full_path == add_map_url %} active{% endif %}" href="{{ add_map_url }}">{% trans "Map" %}</a>
            <a class="nav-link text-muted ml-2" href="/admin/core/chart/add/">{% trans "Chart" %}</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
          <div class="dropdown-menu dropdown-menu-right">
            {% url 'core:user_maps' user.username as user_maps_url %}
            <a class="nav-link text-muted ml-2{% if request.get_full_path == user_maps_url %} active{% endif %}" href="{{ user_maps_url }}">{% trans "My maps" %}</a>
            {% url 'core:user_charts' user.username as user_charts_url %}
            <a class="nav-link text-muted ml-2{% if request.get_full_path == user_charts_url %} active{% endif %}" href="{{ user_charts_url }}">{% trans "My charts" %}</a>
          </div>
        </li>
        <li class="nav-item">
          <a href="{% url 'core:logout' %}" class="nav-link">{% trans "Logout" %}</a>
        </li>
        {% else %}
          <li class="nav-item">
            {% url 'core:login' as login_url %}
             <a href="{{ login_url }}" class="nav-link {% if request.get_full_path == login_url %}active{% endif %}">{% trans "Login" %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container-fluid mt-8">
    {% block content %}{% endblock content %}
  </div>
  <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'bower_components/tether/dist/js/tether.min.js' %}"></script>
  <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'easy_select2/vendor/select2/js/select2.min.js' %}"></script>
  <script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
  <script src="{% static 'bower_components/chart.js/dist/Chart.min.js' %}"></script>
  {% leaflet_js %}
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-74402136-6', 'auto');
    ga('send', 'pageview');
  </script>
  {% block script %}{% endblock script %}
</body>
</html>

templates/chart.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{{ chart.title }}{% endblock title %}
{% block description %}{{ chart.description|default:_("No description provided") }}{% endblock description %}
{% block og-title %}{{ chart.title }}{% endblock og-title %}
{% block og-description %}{{ chart.description|default:_("No description provided") }}{% endblock og-description %}

{% block content %}
  <div>
      <div class="clearfix d-flex flex-column flex-sm-row">
        <h1 class="display-5 text-center col-sm"><wbr>{{ chart.title }}</h1>
        {% if request.user.is_superuser %}
          <a href="/admin/core/chart/{{ chart.pk }}/change/" class="float-right my-auto btn btn-outline-primary edit-map hidden-print">{% trans "Edit" %}</a>
        {% endif %}
      </div>
      <div class="row">
          <div class="col-md-12">
              <p>{{ chart.description }}</p>
              <div id="charts" class="mt-4"></div>
          </div>
      </div>
  </div>
{% endblock content %}
{% block script %}
    <script src="{% static 'bower_components/highcharts/highcharts.js' %}"></script>
    <script src="//platform-api.sharethis.com/js/sharethis.js#property=596324fed14c220014c25d99&product=sticky-share-buttons"></script>
    <script>
        let titles = {{ titles|safe }};
        let data = {{ data|safe }};

        Highcharts.chart('charts', {
            chart: {
                height: 20 * titles.length,
                type: 'bar'
            },
            title: {
                text: ''
            },
            xAxis: {
                categories: titles
            },
            yAxis: {
                min: {{ data_min }},
                title: {
                    text: '{{ chart.title }}'
                }
            },
            legend: {
                reversed: true
            },
            plotOptions: {
                series: {
                    stacking: 'normal'
                }
            },
            series: data
        });
    </script>
{% endblock script %}

templates/list-page.html
{% extends 'base.html' %}
{% load i18n %}
{% load core_tags %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
  <div class="container mb-4">
      <h1 class="display-5 offset-xl-2 offset-lg-1"><wbr>{{ title }}</h1>
      <div class="row">
          {% if params %}
              <ul class="list-inline d-flex flex-wrap col-xl-8 offset-xl-2 col-lg-10 offset-lg-1 col-md-12 no-padding">
                  {% for key, param in params.items %}
                      <li class="list-inline-item d-flex mt-2 badge badge-default">
                          <span class="d-inline-block my-auto mx-2">{{ key }}: {{ param }}</span>
                          <a class="close" aria-label="Close" href="{% update_param request key %}">
                              <span aria-hidden="true">&times;</span>
                          </a>
                      </li>
                  {% endfor %}
              </ul>
          {% endif %}
      </div>
      {% for item in items %}
      <div class="row">
          <div class="card my-2 col-xl-8 offset-xl-2 col-lg-10 offset-lg-1 col-md-12">
              <div class="card-block">
                  {% if item_name == 'plot' %}
                    {% url 'core:plot' item.slug as item_url %}
                  {% elif item_name == 'chart' %}
                    {% url 'core:chart' item.slug as item_url %}
                  {% else %}
                    {% url 'core:map' item.slug as item_url %}
                  {% endif %}
                  <a href="{{ item_url }}"><h2 class="h4 card-title">{% if item.title %}{{ item.title }}{% else %}{{ item.slug }}{% endif %}</h2></a>
                  <p class="card-text text-muted">{{ item.description }}</p>
                  {% for category in item.categories.all %}
                      <a href="?category={{ category.slug }}" class="card-link mr-2">{{ category.title }}</a>
                  {% endfor %}
                   {% if request.user.is_superuser %}
                      <a href="/admin/core/{{ item_name }}/{{ item.pk }}/change/" class="float-right hidden-print  ml-2">{% trans "Edit" %}</a>
                  {% endif %}
                  {% if item.date_of_information %}
                    <a href="?year={{ item.date_of_information|date:'Y' }}" class="card-link float-right ml-2">{{ item.date_of_information|date:'Y' }}</a>
                  {% endif %}
                  {% if item.region %}
                    <a href="?region={{ item.region.pk }}" class="card-link float-right ml-2">{{ item.region.title }}</a>
                  {% elif item_name != 'chart' %}
                    <a href="?region=0" class="card-link float-right ml-2">{% trans "World" %}</a>
                  {% endif %}
              </div>
          </div>
      </div>
      {% endfor %}

      {% if items|length > 10 %}
          <nav aria-label="pagination" class="d-flex justify-content-center mt-4">
              <ul class="pagination">
                  <li class="page-item">
                      <a class="page-link" href="{% update_param request 'p' %}" tabindex="-1">{% trans "First" %}</a>
                  </li>
                  {% if items.has_previous %}
                  <li class="page-item">
                      <a class="page-link" href="{% update_param request 'p' items.previous_page_number %}" rel="prev">{{ items.previous_page_number }}</a>
                  </li>
                  {% endif %}
                  <li class="page-item active">
                      <a class="page-link" href="{% update_param request 'p' items.number %}">{{ items.number }} <span class="sr-only">(current)</span></a>
                  </li>
                  {% if items.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="{% update_param request 'p' items.next_page_number %}" rel="next">{{ items.next_page_number }}</a>
                  </li>
                  {% endif %}
                  <li class="page-item">
                      <a class="page-link" href="{% update_param request 'p' items.paginator.num_pages %}">{% trans "Last" %}</a>
                  </li>
              </ul>
          </nav>
      {% else %}
          {% if items|length == 0 %}
              <p class="my-2 col-xl-8 offset-xl-2 col-lg-10 offset-lg-1 col-md-12">{% blocktrans %}No {{ title }}{% endblocktrans %}</p>
          {% endif %}
      {% endif %}
  </div>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% load socialaccount %}

{% block title %}{% trans 'Login' %}{% endblock title %}
{% block description %}{% trans 'Login or register to create your own maps and charts' %}{% endblock description %}

{% block content %}
  <div class="container mt-6">
  <form action="{% url 'core:login' %}" method="post" class="form-horizontal">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group row">
        <label class="col-sm-3 col-form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
        <div class="col-sm-9">
        {{ field|add_class:"form-control" }}
        {% if field.errors %}
        <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
          {{ field.errors }}
        </div>
        {% endif %}
        </div>
      </div>
    {% endfor %}
    {% if form.non_field_errors %}
      <div class="alert alert-warning col-sm-9 col-sm-offset-3" role="alert">
        {{ form.non_field_errors }}
      </div>
    {% endif %}
    <button type="submit" class="btn btn-primary float-right">{% trans "Log in" %}</button>
  </form>
  <a href="{% provider_login_url "facebook" %}">{% trans "Login with Facebook" %}</a>
  </div>
{% endblock content %}